### ISSUE TITLE
Reproducibility of CGC

### ISSUE THREAD

**Issue by CharliedoD** [XYGaoG/Graph-Condensation-Papers#1]
I greatly appreciate your work on graph condensation and your comprehensive review of the related work. Could you please let me know if the code for CGC, as mentioned in the paper "Rethinking and Accelerating Graph Condensation: A Training-Free Approach with Class Partition," will be open-sourced?

**Comment by XYGaoG** [comment]
Hi,
The paper is currently under review. We plan to open-source the code once the paper has been accepted.

**Comment by CharliedoD** [comment]
I understand and appreciate your position. I look forward to the acceptance of your paper and the release of the code. Best of luck with the review process!
